// <auto-generated />
using System;
using Athos.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Athos.Repository.Migrations
{
    [DbContext(typeof(AthosDbContext))]
    [Migration("20191024135849_comunicado")]
    partial class comunicado
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Athos.Entity.entities.Administradora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<bool>("Excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Administradora");
                });

            modelBuilder.Entity("Athos.Entity.entities.Assunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<bool>("Excluido");

                    b.Property<int>("TipoAssunto");

                    b.HasKey("Id");

                    b.ToTable("Assunto");
                });

            modelBuilder.Entity("Athos.Entity.entities.Comunicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssuntoId");

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<bool>("Excluido");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(3000);

                    b.Property<Guid>("RemetenteId");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoId");

                    b.HasIndex("RemetenteId");

                    b.ToTable("Comunicado");
                });

            modelBuilder.Entity("Athos.Entity.entities.ComunicadoAcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<Guid>("ComunicadoId");

                    b.Property<DateTime>("DataAcao");

                    b.Property<bool>("Excluido");

                    b.Property<Guid>("ExecutorId");

                    b.Property<int>("TipoAcaoComunicado");

                    b.HasKey("Id");

                    b.HasIndex("ComunicadoId");

                    b.HasIndex("ExecutorId");

                    b.ToTable("ComunicadoAcao");
                });

            modelBuilder.Entity("Athos.Entity.entities.Condominio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AdministradoraId");

                    b.Property<bool>("Ativo");

                    b.Property<bool>("Excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradoraId");

                    b.ToTable("Condominio");
                });

            modelBuilder.Entity("Athos.Entity.entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<Guid>("CondominioId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Excluido");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoUsuario");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Athos.Entity.entities.Comunicado", b =>
                {
                    b.HasOne("Athos.Entity.entities.Assunto", "Assunto")
                        .WithMany()
                        .HasForeignKey("AssuntoId");

                    b.HasOne("Athos.Entity.entities.Usuario", "Remetente")
                        .WithMany("Comunicados")
                        .HasForeignKey("RemetenteId");
                });

            modelBuilder.Entity("Athos.Entity.entities.ComunicadoAcao", b =>
                {
                    b.HasOne("Athos.Entity.entities.Comunicado", "Comunicado")
                        .WithMany("ComunicadosAcoes")
                        .HasForeignKey("ComunicadoId");

                    b.HasOne("Athos.Entity.entities.Usuario", "Executor")
                        .WithMany("ComunicadosAcoes")
                        .HasForeignKey("ExecutorId");
                });

            modelBuilder.Entity("Athos.Entity.entities.Condominio", b =>
                {
                    b.HasOne("Athos.Entity.entities.Administradora", "administradora")
                        .WithMany("Condominios")
                        .HasForeignKey("AdministradoraId");
                });

            modelBuilder.Entity("Athos.Entity.entities.Usuario", b =>
                {
                    b.HasOne("Athos.Entity.entities.Condominio", "Condominio")
                        .WithMany("Usuarios")
                        .HasForeignKey("CondominioId");
                });
#pragma warning restore 612, 618
        }
    }
}
